version: '3.8'

services:
  db:
    container_name: db-container
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: carteira
    ports:
      - 3306:3306
    volumes:
      - carteira_data:/var/lib/mysql

volumes:
  carteira_data:
